/**
fruitMap.h file
   This is a header file designed to store the map<> containers used by
    WorldFruit.cpp for both ease of access, modifiability, to demonstrate understanding of 
    header files, and to simply keep WorldFruit.cpp clean of ugly walls of strings.

    This file uses map<> containers to store the values of locations and their fruits, following this example: 
      map<key value: country or state, mapped value: fruits>

*/

#include <map>
#include <string>

using namespace std;

 //North America
map<string, string> fruitsNA = {
    //Canadian Provinces/Territories
   {"ALBERTA","Gooseberries, Blueberries, Saskatoons, and Apricots."},
   {"BRITISH COLOMBIA","Apples, Plums, Peaches, and Grapes."},
   {"MANITOBA","Apples, Plums, Nectarines, Pears."},
   {"NEW BRUNSWICK","Strawberries, Currants, Blackberries, and Bearberries."},
   {"NEWFOUNDLAND AND LABRADOR","Raspberries, Strawberries, Lingonberries, and Cloudberries"},
   {"NOVA SCOTIA","Grapes, Strawberries, Plums, and Cranberries."},
   {"ONTARIO","Pears, Serviceberries, Grapes, and Apples."},
   {"PRINCE EDWARD ISLAND","Cranberries, Currants, Blueberries, and Haskap Berries"},
   {"QUEBEC","Gooseberries, Currants, Apples, and Strawberries."},
   {"SASKATCHEWAN","Saskatoons, Cranberries, Plums, and Buckthorn Berries."},
   {"NORTHWEST TERRITORIES","Currants, Bearberries, Cloudberries, and Currants."},
   {"NUNAVUT","Raspberries, Blackberries, Currants, and Cloudberries."},
   {"YUKON","Raspberries, Strawberries, Salmonberries, and Strawberries."},
   //United States of American States
  {"PENNSYLVANIA", "Pawpaw, American Persimmon, Wild Plum, and Red Mulberry."},
  {"NEW YORK", "Apples, Raspberries, Blackberries, and Strawberries."},
  {"CONNECTICUT", "Apples, Peaches, and Pears."},
  {"VERMONT", "Apples, Blueberries, Apricot, and Pears."},
  {"NEW HAMPSHIRE", "Apples, Blueberries, Apricot, and Pears."},
  {"MASSACHUSETTS", "Cranberries, Blueberries, and Grapes."},
  {"RHODE ISLAND", "Greening Apples."},
  {"MAINE", "Blueberries, Plums, and Chokeberries."},
  {"MARYLAND", "Apples, Cherries, and Grapes."},
  {"DELAWARE", "Strawberries and Peaches."},
  {"NEW JERSEY", "Tomatoes, Cucumbers, and Olives."},
  {"VIRGINIA", "Tomatoes, Grapes, Cucumbers, and Apples."},
  {"NORTH CAROLINA", "Apples, Peaches, and Pecans."},
  {"SOUTH CAROLINA", "Apples, Peaches, Plums."},
  {"GEORGIA", "Apples, Watermelon, Pecans, and Peaches."},
  {"FLORIDA", "Avocado, Mango, Fig, and Citrus."},
  {"ALABAMA","Pecans, Blackberries, Peaches, and Muscadines."},
  {"OHIO","Pawpaw, Elderberries, Perimmons, and Black Raspberries."},
  {"KENTUCKY","Blueberries, Strawberries, Pawpaw, and Kiwi."},
  {"WEST VIRGINIA","Golden Apples, Peaches, Blueberries, and Watermelon."},
  {"TENNESSEE","Tomatoes, Bell Peppers, Cantaloupe, and Cherries."},
  {"INDIANA","Pears, Plums, Apples, and Black Cherries."},
  {"MICHIGAN","Cherries, Beans, Cucumber, and Peaches."},
  {"ILLINOIS","Goldrush Apple, Strawberries, Plums, and Nuts."},
  {"WISCONSIN","Cranberries, Cherries, Bush Fruits, and Bitter Melon."},
  {"MINNESOTA","Honeycrisp Apples, Blueberries, Watermelons, and Grapes."},
  {"IOWA","Hawkeye Apples, Pawpaw, Cherries, and Corn."},
  {"MISSOURI","Gooseberries, Currants, Apricots, and Nectarines."},
  {"ARKANSAS","Watermelon, Pears, Figs, and Black Apples."},
  {"MISSISSIPPI","Oranges, Figs, Gala Apples, and Plums."},
  {"LOUISIANA","Strawberries, Persimmons, Blackberries, and Tomatoes."},
  {"TEXAS","Grapefruit, Peppers, Cucumbers, and Mayhaw."},
  {"OKLAHOMA","Apples, Peaches, Peaches, and Elderberries."},
  {"KANSAS","Plums, Persimmons, Grapes, and Mulberries."},
  {"NEBRASKA","Pears, Plums, Grapes, and Cherries."},
  {"SOUTH DAKOTA","Cherries, Apples, Plums, Cantaloupes."},
  {"NORTH DAKOTA","Apricots, Pears, Currants, and Apples."},
  {"NEW MEXICO","Blackberries, Cherries, Peaches, and Apricots."},
  {"COLORADO","Plums, Strawberries, Cherries, and Apricots."},
  {"WYOMING","Chokecherries, Plums, Peaches, and Grapes."},
  {"MONTANA","Apricots, Plums, Pears, and Plums."},
  {"IDAHO","Pears, Huckleberries, Nectarines, and Grapes."},
  {"UTAH","Plums, Pears, Peaches, and Apricots."},
  {"ARIZONA","Melons, Lemons, Oranges, and Tomatoes."},
  {"CALIFORNIA","Grapes, Berries, Avocado, and Figs."},
  {"OREGON","Blueberries, Grapes, Pears, and Cherries."},
  {"WASHINGTON","Grapes, Apricots, Marionberries, and Blackberries."},
  {"NEVADA","Apricots, Plums, Pears, and Apples."},
  {"HAWAII","Mango, Coconuts, Rambutans, Lychee, and Guava."},
  {"ALASKA","Salmonberry, Currants, Lingonberries, and Strawberries."},
  //Central American countries
 {"MEXICO","Mango, Peppers, Papaya, and Avocado."},
 {"PANAMA","Mango, Jackfruit, Avocado, and Papaya."},
 {"NICARAGUA","Bananas, Lemon, Pineapple, and Mango."},
 {"HONDURAS","Plantain, Orange, Passionfruit, and Chili Peppers."},
 {"GUATEMALA","Jocote, Mango, Star Fruit, Papaya."},
 {"EL SALVADOR","Loquat, Tamarind, Guava, and Mango."},
 {"COSTA RICA","Passionfruit, Soursop, Papaya, and Dragon Fruit."},
 {"BELIZE","Soursop, Breadfruit, Dragon Fruit, and Papaya."},
 //Carribean Islands, although, just the recognized Countries (there are hundreds of islands)
{"ANTIGUA AND BARBUDA","Coconut, Bananas, Cucumbers, and Pineapple."},
{"DOMINICA","Guava, Pineapples, Breaduit, and Passionfruit."},
{"THE BAHAMAS","Soursop, Papaya, Limes, and Seagrapes."},
{"BARBADOS","Passionfruit, Breadfruit, Goosebrrries, and Guava."},
{"CUBA","Mango, Guava, Bananas, and Avocado."},
{"DOMINICAN REPUBLIC","Soursop, Sapote, Avocado, and Pineapple."},
{"GRENADA","Plantains, Mango, Passionfruit, and breadfruit."},
{"HAITI","Avocado, Guava, Coconut, and Mango."},
{"JAMAICA","Mango, Ackee, Jackfruit, and Plums."},
{"ST. KITTS AND NEVIS","Soursop, Breadfruit, Mango, and Bananas."},
{"ST. LUCIA","Coconut, Apples, Guava, and Papaya."},
{"ST. VINCENT AND GRENADINES","Bananas, Soursop, Dragon Fruit, and Pineapples."},
{"TRINIDAD AND TOBAGO","Papaya, Coconut, Ackee, and Breadfruit."},
};

//South America
map<string, string> fruitsSA = {
    {"COLOMBIA", "Granadilla, Pitaya, Zapote, and Lulo."},
    {"VENEZUELA", "Passionfruit, Mango, Guava, and and Bananas."},
    {"BRAZIL", "Acai, Guarana, Jabuticaba, and Papaya."},
    {"ECUADOR", "Soursop, Plantain, Pepino, and Naranjilla."},
    {"PERU", "Camu Camu, Chirimoya, Passionfruit, and Cocona."},
    {"BOLIVIA", "Coconut, Banana, Kiwi, and Pineapples."},
    {"CHILE", "Grapes, Papaya, Apples, and Lucama."},
    {"GUYANA", "Pitanga, Spice Mango, Golden Apple, and Passionfruit."},
    {"SURINAME", "Milk Fruit, Surinam Cherry, Coconut, and Cherries."},
    {"FRENCH GUIANA", "Lemon, Orange, Chilli Peppers, and Apricots."},
    {"ARGENTINA", "Tangerines, Plums, Oranges, and Apples."},
    {"URUGUAY", "Guabiyu, Oranges, Blueberries, and Apples."},
};

//Africa
map<string, string> fruitsAF = {
    {"ALGERIA","Figs, Dates, Olives and Watermelons."},
    {"ANGOLA","Bananas, Pineapples, Mangoes, and Avocado."},
    {"BENIN","Oranges, Kiwis, Pineapples, and Cayenne Pappers."},
    {"BOTSWANA","Peaches, Watermelons, Wild Melons, and Paw-Paw."},
    {"BURKINA FASO","Papayas, Mangoes, Bananas, and Pineapples."},
    {"BURUNDI","Apples, Pears, Grapes, and Bananas."},
    {"CABO VERDE","Coconuts, Bananas, Quince, and Papayas."},
    {"CAMEROON","Watermelons, Peppers, Dates, and Figs."},
    {"CENTRAL AFRICAN REPUBLIC","Plantains, Bananas, Okra, and Plantains."},
    {"CHAD","Mangoes, Cashews, Dates, and Corn."},
    {"COMOROS","Bananas, Coconuts, Plantains, and Coffee."},
    {"DEMOCRATIC REPUBLIC OF THE CONGO","Avocado, Guavas, Mangoes, and Papayas."},
    {"COTE D'IVOIRE","Mangoes, Pineapples, Papayas, and Kiwis."},
    {"REPUBLIC OF THE CONGO","Maniac, Bananas, Plantains, and Pineapples."},
    {"DJIBOUTI","Dates, Tomatoes, Bananas, and Wild Melons."},
    {"EGYPT","Watermelons, Figs, Prickly Pears, and Oranges."},
    {"EQUATORIAL GUINEA","Palm Fruits, Plantains, Coconuts, and Atanga."},
    {"ERITREA","Beles, Dates, Oranges, and Pomegranates."},
    {"ESWATINI","Bananas, Pitayas, Strawberries, and Lychee."},
    {"ETHIOPIA","Lemons, Bananas, Apples, and Pineapples."},
    {"GABON","Pineapples, Coconuts, Avocado, and Bananas."},
    {"GAMBIA","Coconut, Soursop, Guava, and Plums."},
    {"GHANA","Bananas, Oranges, Papayas, and Pineapples."},
    {"GUINEA","Oranges, Lemons, Pineapplesm and Bananas."},
    {"GUINEA-BISSAU","Cashews, Papayas, Mangoes, and Palm Fruits."},
    {"KENYA","Passionfruits, Mangoes, Bananas, and Paw-Paws."},
    {"LESOTHO","Apples, Grapes, Oranges, and Peaches."},
    {"LIBERIA","Lemons, Bananas, Pineapples, and Coconuts."},
    {"LIBYA","Apricots, Figs, Grapes, and Olives."},
    {"MADAGASCAR","Guavas, Papayas, Jackfruit, and Bananas."},
    {"MALAWI","Guavas, Papayas, Tangerines, and Avocado."},
    {"MALI","Mangoes, Oranges, Bananas, and Kiwis."},
    {"MAURITANIA","Dates, Nectarines, Watermelons, and Honeydew Melons."},
    {"MAURITIUS","Custard Apples, Coconuts, Guavas, and Passionfruits."},
    {"MOROCCO","Avocado, Blueberries, Pomegranates, and Peaches."},
    {"MOZAMBIQUE","Baobab Fruit, Liana Fruit, Oranges, and Papaaya."},
    {"NAMIBIA","Grapes, Lemons, Dates, and Blueberries."},
    {"NIGER","Watermelons, Peaches, Bananas, and Plums."},
    {"NIGERIA","Bananas, Pineapples, Watermelons, Apples."},
    {"RWANDA","Avocado, Bananas, Pineapples, and Mangoes."},
    {"SAO TOME AND PRINCIPE","Breadfruit, Bananas, Pineapples, and Papaya."},
    {"SENEGAL","Maad Fruit, Baobab Fruit, Peppers, and Mangoes."},
    {"SEYCHELLES","Bananas, Pineapples, Passionfruit, and Papayas."},
    {"SIERRA LEONE","Mangoes, Bananas, Oranges, and Mende Fruit."},
    {"SOMALIA","Bananas, Papayas, Apples, and Grapes."},
    {"SOUTH AFRICA","Avocado, Bananas, Peaches, and Oranges."},
    {"SOUTH SUDAN","Pineapples, Oranges, Watermelons, and Grapes."},
    {"SUDAN","Guavas, Date Palm, Bananas, and Citrus."},
    {"TANZANIA","Mangoes, Bananas, Clementines, and Jackfruit."},
    {"TOGO","Wild Melons, Apples, Pears, and Baobab Fruit."},
    {"TUNISIA","Figs, Grapes, Pomegranates, and Peaches."},
    {"UGANDA","Passionfruit, Watermelons, Avocado, and Papayas."},
    {"ZAMBIA","Apples, Bananas, Pears, and Plums."},
    {"ZIMBBABWE","Grapefruit, Mandarins, Passionfruit, and Coconuts."},
};

//Australia
map<string, string> fruitsAU = {
    {"ASHMORE AND CARTIER ISLANDS", "Wild Fruits"},
    {"AUSTRALIAN CAPITAL TERRITORY", "Lemons, Persimmons, Privets, and Peaches."},
    {"AUSTRALIAN ANTARCTIC TERRITORY", "Nothing!"},
    {"COCOS ISLANDS", "Coconuts, Apples, Avocados, and Pittieri Fruits."},
    {"CORAL SEA ISLANDS", "Bananas, Avocados, Mangoes, and Pineapples."},
    {"CHRISTMAS ISLAND", "Bananas, Mangoes, Guava, and Limes."},
    {"HEARD AND MCDONALD ISLANDS", "Wild Fruits."},
    {"JERVIS BAY TERRITORY", "Bush Berries."},
    {"NEW SOUTH WALES", "Grapes, Peaches, Plums, and Apples."},
    {"NORFOLK ISLAND", "Guavas, Watermelons, Loquats, and Strawberries."},
    {"NORTHERN TERRITORY", "Lemons, Limes, Pummelo, and Dragon Fruits."},
    {"SOUTH AUSTRALIA", "Persimmons, Avocados, Cherries, and Apricots."},
    {"TASMANIA", "Apples, Pears, Peaches, and Bush Berries."},
    {"QUEENSLAND", "Bananas, Mangoes, Durians, and Jackfruits."},
    {"VICTORIA", "Peaches, Bush Berries, Apples, and Pears."},
    {"WESTERN AUSTRALIA", "Avocadoes, Nectarines, Kiwis, and Grapes."},
};